### ISSUE TITLE
bsc fork 10087723 失败

### ISSUE THREAD

**Issue by ghost** [W2Ning/XSURGE_FlashLoan_Vul#1]
我在bsc fork 10087723 失败，请问你是怎么fork bsc指定区块的？
我用的：
npx ganache-cli --fork  https://bsc.getblock.io/mainnet/?api_key=xxx@10087723

**Comment by altabre** [comment]
同问

**Comment by NonNobody** [comment]
我也遇到指定高度fork失败，如果不指定高度是没问题的：
```
npx ganache-cli -f https://bsc-dataseed.binance.org -a 1
```
但是指定高度会报错：
```
npx ganache-cli -f https://bsc-dataseed.binance.org@10080000 -a 1

Ganache CLI v6.12.2 (ganache-core: 2.13.2)
Error: The fork provider errored when checking the nonce for account 0x0784b7211f0aa57082c53164645d56075b8aeedb: Returned error: missing trie node 9bd4b3d0e360fc2cc248032db20c090669847a8a4e45a956f6501fa10ad7e0a6 (path )
    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2094303
    at Object._fireError (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:67075)
    at s (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:114003)
    at a (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2108928)
    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2093154
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: null
}
```

**Comment by W2Ning** [comment]
统一回复下吧
解决方案有两个：

1.本地起全节点
2.找找有没有节点服务商提供`Archive`的fullnode,找到了也记得告诉我，靴靴

**Comment by NonNobody** [comment]
https://www.quicknode.com/chains/bsc
quicknode提供archive模式，但比较贵，250刀一个月，留下没钱的泪水……

**Comment by W2Ning** [comment]
> https://www.quicknode.com/chains/bsc
> quicknode提供archive模式，但比较贵，250刀一个月，留下没钱的泪水……

quicknode我信用卡都绑了，250刀直接劝退😟
