### ISSUE TITLE
hi大佬，我ganache fork bsc的时候出现了问题，而以太坊链可以正常fork

### ISSUE THREAD

**Issue by cradle0fFilth** [W2Ning/XSURGE_FlashLoan_Vul#2]
我的命令是：ganache-cli --fork https://bsc-dataseed.binance.org/@1008772
错误信息是：
Error: The fork provider errored when checking the nonce for account 0x739ea52b5d0cd85ce496ed01531859f175ef482b: Returned error: missing trie node 03be601979c1357a88195377dfdbd215861d2258cd14715b0333d88d5b556631 (path )
    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2094303
    at Object._fireError (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:67075)
    at s (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:114003)
    at a (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2108928)
    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2093154
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  data: null

请问您fork的时候有遇到同款问题吗？
换成moralis的第三方rpc也是同样的问题，bsc链或许不支持@block的方式fork？而不加这个后缀是可以的。我查询了所有google 的信息但仍然被卡在这里，被迫向您求助了（打扰）

**Comment by W2Ning** [comment]
BSC可以用@block的方法fork
但是需要找到Archive的节点才可以
之前的ISSUE我不该close的...

**Comment by W2Ning** [comment]
我reopen了之前的issue
上面做了统一的回复

**Comment by W2Ning** [comment]
![image](https://user-images.githubusercontent.com/33406415/140497391-40bb8956-6f1f-48a7-98ef-72bc732e11df.png)
选Speedy Nodes好像可以 
但是这个我没法登录..
